English translation for v1.1.5
ivan-work/evolution-web pull request #91
Opened 2021-02-24 10:45 UTC by JuniorTheF

автор не претендует на полную корректность перевода, но сделал максимально аккуратно по мере знания языка

2021-02-24 16:44 UTC, ivan-work requested changes

2021-02-24 16:44 UTC, ivan-work commented on i18n/en-en.yml
> +    source: Symbiont
Wrong indent. Yes, it's important.

2021-02-24 17:02 UTC, JuniorTheF commented on i18n/en-en.yml
> +    source: Symbiont
fixed

2021-02-25 12:27 UTC, ivan-work approved these changes
Thanks, will merge when I make language selector

2021-02-26 03:32 UTC, ivan-work requested changes

2021-02-26 03:32 UTC, ivan-work commented on i18n/en-en.yml
> + Log:
please add two spaces: `  Log:`

2021-02-26 03:32 UTC, ivan-work commented on i18n/en-en.yml
> + Messages:
please add two spaces, not the one: `  Messages:`

2021-02-26 03:49 UTC, ivan-work commented
merged, will it spaces myself

2021-02-26 03:49 UTC, merged